"""Watcher: a small always-on-top monitoring window for Jenkins jobs (and more)."""

# Base version: bump manually for a notable, intentional milestone. Day-to-day
# builds don't need (and shouldn't require) a manual bump - see BUILD_NUMBER
# below, which is what actually changes on every merge to main and is what
# makes update detection work without remembering to edit this file.
__version__ = "0.1"

try:
    # Generated by scripts/build_macos_app.sh (and the release workflow)
    # right before PyInstaller runs; not committed to source control (see
    # .gitignore). Absent in a plain source checkout / dev run.
    from watcher._build_version import BUILD_NUMBER
except ImportError:
    BUILD_NUMBER = "0"

#: Full, comparable release version: "<base>.<build_number>", e.g. "0.1.47".
#: This is what gets compared against GitHub releases for update checks, and
#: what's embedded into the built .app's Info.plist.
__full_version__ = f"{__version__}.{BUILD_NUMBER}"
