#!/usr/bin/env bash
#
# Builds Watcher.app using PyInstaller: a self-contained macOS app bundle
# (with its own icon and identity, instead of the generic Python "rocket")
# that can be pinned to the Dock or kept in /Applications.
#
# An earlier version of this script built a hand-rolled bundle that just
# exec'd the system python3 from a launcher script. That approach hit an
# unresolved machine-specific Tk/Cocoa rendering bug when launched via
# Finder/the Dock (widgets existed and responded to clicks but nothing was
# painted). PyInstaller sidesteps it by embedding a proper, self-contained
# Python runtime as a correctly structured, signed app bundle rather than
# re-executing the system interpreter from a script.
#
# Usage:
#   ./scripts/build_macos_app.sh [destination-dir]
#
# destination-dir defaults to ./dist (git-ignored). Common choices:
#   ./scripts/build_macos_app.sh ~/Applications
#   ./scripts/build_macos_app.sh /Applications

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "error: this script only builds a macOS .app bundle (requires Darwin)." >&2
    exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
icon_path="${repo_root}/packaging/macos/Watcher.icns"

dest_arg="${1:-"${repo_root}/dist"}"
mkdir -p "${dest_arg}"
dest_dir="$(cd "${dest_arg}" && pwd)"

# Prefer a project-local virtualenv's interpreter/pyinstaller if one exists.
# Fall back to whatever's on PATH otherwise.
python_bin="python3"
for venv_candidate in "${repo_root}/.venv/bin/python3" "${repo_root}/venv/bin/python3"; do
    if [[ -x "${venv_candidate}" ]]; then
        python_bin="${venv_candidate}"
        break
    fi
done

if ! "${python_bin}" -m PyInstaller --version >/dev/null 2>&1; then
    echo "error: PyInstaller is not installed for ${python_bin}." >&2
    echo "       Install it with: ${python_bin} -m pip install pyinstaller" >&2
    exit 1
fi

# Build number: an auto-incrementing counter (no manual bump needed) so
# every merge to main produces a build the in-app update checker can detect,
# even when nobody touched watcher/__init__.py's __version__. The release
# workflow passes WATCHER_BUILD_NUMBER explicitly (commit count at build
# time); a local dev build falls back to computing it the same way, or "0"
# outside a git checkout.
build_number="${WATCHER_BUILD_NUMBER:-$(git -C "${repo_root}" rev-list --count HEAD 2>/dev/null || echo 0)}"
base_version="$("${python_bin}" -c "
import re
with open('${repo_root}/watcher/__init__.py') as f:
    print(re.search(r'__version__ = \"([^\"]+)\"', f.read()).group(1))
")"
full_version="${base_version}.${build_number}"

cat > "${repo_root}/watcher/_build_version.py" <<EOF
"""Auto-generated by scripts/build_macos_app.sh - do not edit by hand."""

BUILD_NUMBER = "${build_number}"
EOF

echo "Building Watcher v${full_version} (build ${build_number})"

# Kill any already-running instance first. PyInstaller builds into a fresh
# ./build and ./dist each run, but a still-running process keeps using its
# already-open (now-unlinked) executable -- rebuilding does NOT replace what
# a running process is executing. Reopening the Dock icon (or double-
# clicking the app again) while an old instance is alive just reactivates
# that stale, already-running window instead of starting a fresh one with
# the new code, which looks exactly like "the rebuild didn't change
# anything".
running_pids="$(pgrep -f "${dest_dir}/Watcher.app/Contents/MacOS/Watcher" || true)"
if [[ -n "${running_pids}" ]]; then
    echo "Stopping existing Watcher process(es): ${running_pids//$'\n'/, }"
    while IFS= read -r pid; do
        [[ -n "${pid}" ]] && kill "${pid}" 2>/dev/null || true
    done <<< "${running_pids}"
    sleep 1
fi

work_dir="${repo_root}/build/pyinstaller"
spec_dir="${repo_root}/build"
rm -rf "${dest_dir}/Watcher.app" "${work_dir}"

"${python_bin}" -m PyInstaller \
    --windowed \
    --noconsole \
    --name=Watcher \
    --icon="${icon_path}" \
    --distpath="${dest_dir}" \
    --workpath="${work_dir}" \
    --specpath="${spec_dir}" \
    --noconfirm \
    "${repo_root}/main.py"

# PyInstaller's generated Info.plist has no version info; inject it so the
# build number (and Finder's "Get Info" version) matches what the in-app
# update checker compares against.
plist="${dest_dir}/Watcher.app/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${full_version}" "${plist}" 2>/dev/null \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${full_version}" "${plist}"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${build_number}" "${plist}" 2>/dev/null \
    || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${build_number}" "${plist}"

echo
echo "Built ${dest_dir}/Watcher.app (v${full_version})"
echo "Drag it to /Applications, or into the Dock, to pin it like any other app."
echo "Fully quit any already-running Watcher window before relaunching, so you're"
echo "not looking at a stale instance from before this rebuild."
