#!/usr/bin/env bash
#
# Builds the native SwiftUI Watcher.app: the Swift UI (macos/) plus the Python
# engine frozen with PyInstaller and embedded as a sidecar, which the app
# launches on startup (see macos/Sources/WatcherKit/CoreProcess.swift).
#
# The older Tk build (scripts/build_macos_app.sh) also produces Watcher.app,
# so the two overwrite each other if they share a destination directory.
#
# Usage:
#   ./scripts/build_native_app.sh [destination-dir]   # defaults to ./dist
#
# Environment:
#   WATCHER_BUILD_NUMBER   build number (defaults to the git commit count)
#   WATCHER_SIGN_IDENTITY  codesign identity (defaults to "-", ad-hoc)

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "error: this script only builds a macOS .app bundle (requires Darwin)." >&2
    exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
icon_path="${repo_root}/packaging/macos/Watcher.icns"

dest_arg="${1:-"${repo_root}/dist"}"
mkdir -p "${dest_arg}"
dest_dir="$(cd "${dest_arg}" && pwd)"

python_bin="python3"
for venv_candidate in "${repo_root}/.venv/bin/python3" "${repo_root}/venv/bin/python3"; do
    if [[ -x "${venv_candidate}" ]]; then
        python_bin="${venv_candidate}"
        break
    fi
done
if ! "${python_bin}" -m PyInstaller --version >/dev/null 2>&1; then
    echo "error: PyInstaller is not installed for ${python_bin}." >&2
    echo "       Install it with: ${python_bin} -m pip install pyinstaller" >&2
    exit 1
fi

build_number="${WATCHER_BUILD_NUMBER:-$(git -C "${repo_root}" rev-list --count HEAD 2>/dev/null || echo 0)}"
base_version="$("${python_bin}" -c "
import re
with open('${repo_root}/watcher/__init__.py') as f:
    print(re.search(r'__version__ = \"([^\"]+)\"', f.read()).group(1))
")"
full_version="${base_version}.${build_number}"

cat > "${repo_root}/watcher/_build_version.py" <<PYEOF
"""Auto-generated by scripts/build_native_app.sh - do not edit by hand."""

BUILD_NUMBER = "${build_number}"
PYEOF

echo "Building native Watcher v${full_version} (build ${build_number})"

work_dir="${repo_root}/build/native"
rm -rf "${work_dir}" "${dest_dir}/Watcher.app"
mkdir -p "${work_dir}"

echo "==> Freezing the Python core"
"${python_bin}" -m PyInstaller \
    --console \
    --name=watcher-core \
    --distpath="${work_dir}/core" \
    --workpath="${work_dir}/pyinstaller" \
    --specpath="${work_dir}" \
    --paths="${repo_root}" \
    --noconfirm \
    "${repo_root}/watcher/api/__main__.py"

echo "==> Building the SwiftUI app"
swift build -c release --package-path "${repo_root}/macos"
swift_bin="$(swift build -c release --package-path "${repo_root}/macos" --show-bin-path)/WatcherApp"

app="${dest_dir}/Watcher.app"
mkdir -p "${app}/Contents/MacOS" "${app}/Contents/Resources"
cp "${swift_bin}" "${app}/Contents/MacOS/Watcher"
cp -R "${work_dir}/core/watcher-core" "${app}/Contents/Resources/watcher-core"
cp "${icon_path}" "${app}/Contents/Resources/Watcher.icns"

cat > "${app}/Contents/Info.plist" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>Watcher</string>
    <key>CFBundleDisplayName</key><string>Watcher</string>
    <key>CFBundleIdentifier</key><string>com.storercd.watcher</string>
    <key>CFBundleExecutable</key><string>Watcher</string>
    <key>CFBundleIconFile</key><string>Watcher</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${full_version}</string>
    <key>CFBundleVersion</key><string>${build_number}</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>NSHighResolutionCapable</key><true/>
    <key>NSPrincipalClass</key><string>NSApplication</string>
</dict>
</plist>
PLISTEOF

echo "==> Signing (${WATCHER_SIGN_IDENTITY:--})"
codesign --force --deep --sign "${WATCHER_SIGN_IDENTITY:--}" "${app}"

echo
echo "Built ${app} (v${full_version})"
